name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  solutionPath:
    required: true
    description: 'input solution file path here'
runs:
  using: 'node12'
  main: 'dist/index.js'
