name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  lint_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run all
  e2e_test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ ubuntu-latest, windows-latest, macOS-latest ]
        dotnet-version: [ '3.1', '5.0', '6.0' ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - uses: ./
        with:
          solutionPath: TestSolution/TestSolution.sln
          failOnIssue: '0'
      # Reproduce second time execution on self-hosted runner
      - uses: ./
        with:
          solutionPath: TestSolution/TestSolution.sln
          failOnIssue: '0'
  package:
    needs: [lint_test, e2e_test]
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build && npm run package
      - name: Commit compiled code
        run: |
          git config --local user.name 'GitHub Actions'
          git config --local user.mail 'action@github.com'
          git add .
          git diff --exit-code --quiet || git commit -m 'Compile' && git push origin ${{ github.head_ref }}
